image: docker:latest

variables:
  api: "http://localhost:3005"
  # docker in docker specific
  DOCKER_DRIVER: overlay2
  # project vars
  REGISTRY_URL: "registry.gitlab.com/ldso18-19/t3g1"

services:
  - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .jest
  - mobile/node_modules/
  - server/node_modules/
  - web-app/node_modules/

stages:
  - lint
  - test
  - build
  - deploy
  - cleanup

lint_mobile:
  image: node:alpine
  stage: lint
  before_script:
    - cd mobile
    - yarn
  script:
    - yarn run lint

lint_web:
  image: node:alpine
  stage: lint
  before_script:
    - cd web-app
    - yarn
  script:
    - yarn run lint

lint_server:
  image: node:alpine
  stage: lint
  before_script:
    - cd server
    - npm install
  script:
    - npm run lint

deploy_mobile:
  image: node:alpine
  stage: deploy
  before_script:
    - cd mobile
    - printenv >> .env
    - yarn
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
  only:
    - master
    - develop

test_mobile:
  image: node:alpine
  stage: test
  before_script: # Add the other dependency instalations later
  - cd mobile
  - printenv >> .env
  - yarn
  script:
    - yarn test-ci

build_server:
  image: docker:stable
  stage: build
  allow_failure: true
  before_script:
    - cd server
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $REGISTRY_URL/server:$CI_COMMIT_REF_NAME .
    - docker push $REGISTRY_URL/server:$CI_COMMIT_REF_NAME
  # only:
  #   - master
  #   - develop

build_web:
  image: docker:stable
  stage: build
  allow_failure: true
  before_script:
    - cd web-app
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $REGISTRY_URL/web-app:$CI_COMMIT_REF_NAME .
    - docker push $REGISTRY_URL/web-app:$CI_COMMIT_REF_NAME
  # only:
  #   - master
  #   - develop

build_mobile:
  image: docker:stable
  stage: build
  allow_failure: true
  before_script:
    - cd mobile
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $REGISTRY_URL/mobile:$CI_COMMIT_REF_NAME .
    - docker push $REGISTRY_URL/mobile:$CI_COMMIT_REF_NAME
  only:
    - master
    - develop

# server_deploy_staging:
#   stage: deploy
#   before_script:
#     - ssh andre@51.144.252.180 -p $SSH_PRIVATE_KEY
#   script:
#     - cd LDSO
#     - docker-compose up
#     - ./seed
#   only:
#     - master
#     - develop
 