# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
  api: "http://localhost:3005"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - mobile/node_modules/
  - server/node_modules/
  - web-app/node_modules/

stages:
  - lint
  - build
  - test
  - cleanup

test_mobile:
  stage: test
  before_script: # Add the other dependency instalations later
  - cd mobile
  - printenv >> .env
  - yarn
  script:
    - yarn test-ci

lint_mobile:
  stage: lint
  script:
    - cd mobile
    - yarn install
    - yarn run lint

