# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:alpine

variables:
  api: "http://localhost:3005"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .jest
  - mobile/node_modules/
  - server/node_modules/
  - web-app/node_modules/

stages:
  - lint
  - build
  - test
  - deploy
  - cleanup

lint_mobile:
  stage: lint
  before_script:
    - cd mobile
    - yarn
  script:
    - yarn run lint

lint_web:
  stage: lint
  before_script:
    - cd web-app
    - yarn
  script:
    - yarn run lint

deploy_mobile:
  stage: deploy
  before_script:
    - cd mobile
    - printenv >> .env
    - yarn
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
  only:
    - master
    - develop

test_mobile:
  stage: test
  before_script: # Add the other dependency instalations later
  - cd mobile
  - printenv >> .env
  - yarn
  script:
    - yarn test-ci

