version: '3.4'

services:
  web-app:
    image: web-app
    command: yarn start
    build:
      context: ./web-app
      target: build-stage
    volumes:
      - ./web-app/:/user/src/app
      - /user/src/app/node_modules
    container_name: web-app
    ports:
      - '4200:3000'
    environment:
      - REACT_APP_ENDPOINT

  server:
    image: server
    build:
      context: ./server
      target: build-stage
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: server
    ports:
      - '3000:3000'
    links:
      - mongo:mongo
    depends_on:
      - mongo
    environment:
      - DB_HOST
      - DB_PORT
 
  mongo:
   image: mongo:4.0.1
   container_name: mongo
   ports:
     - "27017:27017"
   volumes:
     - ./docker/data/mongo:/data/db

  mongo_seed:
    image: mongo:4.0.1
    links:
      - mongo
    volumes:
      - ./server/resources:/home
    command: bash -c "mongoimport --host mongo --db up --collection User --file /home/users_seed.json --drop --jsonArray && mongoimport --host mongo --db up --collection Faculty --file /home/faculties_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection SocialProject --file /home/projects_seed.json --jsonArray --drop --maintainInsertionOrder && mongoimport --host mongo --db up --collection Statistics --file /home/statistics_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection ResearchCenter --file /home/research_centers_seed.json --jsonArray --drop"
    depends_on:
      - mongo