version: '3.4'

services:
  web-app:
    image: web-app
    command: yarn start
    build:
      context: ./web-app
      target: build-stage
    volumes:
      - ./web-app/:/user/src/app
      - /user/src/app/node_modules
    container_name: web-app
    ports:
      - '3000:3000'

  server:
    image: server
    command: yarn dev
    build:
      context: ./server
      target: build-stage
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: server
    ports:
      - '3000:3000'
    links:
        - mongo:mongo
    depends_on:
        - mongo
 
  mongo:
   image: mongo:latest
   container_name: mongo
   ports:
     - "27017:27017"
   volumes:
     - ./docker/data/mongo:/data/db
