version: '3.4'

services:
  mobile:
    image: mobile
    command: yarn start 
    build:
        context: ./mobile
        target: build-stage
    volumes:
        - ./mobile/:/usr/src/app
        - /usr/src/app/node_modules
    container_name: mobile
    ports:
         - '19000:19000'
         - '19001:19001'
         - '19002:19002'
         
  web-app:
    image: web-app
    command: yarn start
    build:
      context: ./web-app
      target: build-stage
    volumes:
      - ./web-app/:/user/src/app
      - /user/src/app/node_modules
    container_name: web-app
    ports:
      - '4200:4200'

  server:
    image: server
    command: yarn dev
    build:
      context: ./server
      target: build-stage
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: server
    ports:
      - '3000:3000'
    links:
        - mongo:mongo
    depends_on:
        - mongo
 
  mongo:
   image: mongo:4.0.1
   container_name: mongo
   ports:
     - "27017:27017"
   volumes:
     - ./docker/data/mongo:/data/db

  mongo_seed:
    image: mongo:4.0.1
    links:
      - mongo
    volumes:
      - ./server/resources:/home
    command: bash -c "mongoimport --host mongo --db up --collection Faculty --file /home/faculties_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection SocialProject --file /home/projects_seed.json --jsonArray --drop"