version: '3.4'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - '80:80'
    depends_on:
      - server-master
     
#  web-app-master: # TODO change
#    image: registry.gitlab.com/ldso18-19/t3g1/web-app:develop
#    ports:
#      - '8000:4200'  
# restart: always

  server-master: # TODO change
    image: registry.gitlab.com/ldso18-19/t3g1/server:develop
    # restart: always
    ports:
      - '3000:3000'
    depends_on:
        - mongo
 
  mongo:
    image: mongo:4.0.1
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./resources:/home
    # restart: always
