version: '3.4'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - '80:80'
    depends_on:
      - server-master
      - web-app-master
      - server-develop
      - web-app-develop
     
  web-app-develop:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/web-app:develop
    container_name: web-app-develop
    restart: unless-stopped
    command: yarn start
    expose:
      - '3000'
    depends_on:
      - server-develop

  web-app-master:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/web-app:master
    container_name: web-app-master
    restart: unless-stopped
    command: yarn start
    expose:
      - '3000'
    depends_on:
      - server-master

  server-develop:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/server:develop
    container_name: server-develop
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - mongo

  server-master:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/server:master
    container_name: server-master
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0.1
    container_name: mongo
    volumes:
      - ./resources:/home
    expose:
      - "27017"
