version: '3.4'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - '80:80'
    depends_on:
      - server-master
      - web-app-master

  web-app-master:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/web-app:master
    container_name: web-app-master
    restart: unless-stopped
    command: yarn start
    expose:
      - '3000'
    depends_on:
      - server-master

  server-master:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t3g1/server:master
    container_name: server-master
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - mongo
    environment:
      - DB_HOST
      - DB_PORT

  mongo:
    image: mongo:4.0.1
    container_name: mongo
    expose:
      - "27017"

  seed-mongo:
    image: mongo:4.0.1
    links:
      - mongo
    volumes:
      - ./resources:/home
    command: bash -c "mongoimport --host mongo --db up --collection Faculty --file /home/faculties_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection SocialProject --file /home/projects_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection Statistics --file /home/statistics_seed.json --jsonArray --drop && mongoimport --host mongo --db up --collection ResearchCenter --file /home/research_centers_seed.json --jsonArray --drop"
    depends_on:
      - mongo